### ISSUE TITLE
Write in register

### ISSUE THREAD

**Issue by floppi-wd** [Cisco-Talos/pyrebox#10]
Hey,

i have read in the docu that is possible to write in the register from the VM. I use Qemu to simulate an old DOS system. Now i want to read/write a register from the VM. I found in your docu the function "api.w_r(cpu_index, regname, val)". In my special case i want to read/write the serial port COM1 (Port adress #3f8). So what is the correct way to initialize the parameter of the function api.w_r(cpu_index, regname, val) to read/write in the this register.

Thanks for helping

**Comment by xabiugarte** [comment]
Hi,

The function "api.w_r(cpu_index, regname, val)" will let you write to general purpose registers by specifying the register name. For example:

api.w_r(0,"EAX",0xABCDABCD)

... will write the hexadecimal value 0xABCDABCD on register EAX.

Nevertheless, this approach doesn't let you write to IO ports. This can be done in the QEMU monitor prompt using the "i" and "o" command, and was not implemented yet on PyREBox. The last commit (dcf812277773bff270f9cbf3ce06ac21a9f32db1) adds this functionality to PyREBox, both in the API (api.r_ioport / api.w_ioport), as well as in the IPython shell (commands iorb, iorw, iord, iowb, ioww, iowd).

Hope you find it useful. The docs should be updated too, so you should find enough  information there.

I am closing this issue, please reopen it if you have issues.
