### ISSUE TITLE
sleuthkit python2

### ISSUE THREAD

**Issue by s0i37** [Cisco-Talos/pyrebox#101]
Hello. I have built pyrebox.
```
~/src/pyrebox(master*) » ./pyrebox-i386                                            24.01.2020 09:41:26
Traceback (most recent call last):
  File "/home/soier/src/pyrebox/pyrebox/init.py", line 26, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable
./pyrebox-i386: line 3: 19541 Segmentation fault      LD_LIBRARY_PATH=$BASEDIR/sleuthkit/tsk/.libs:$LD_LIBRARY_PATH $BASEDIR/qemu/i386-softmmu/qemu-system-i386 "$@"
(pyrebox_venv)
```
It seems `sleuthkit` uses python2. Despite my /usr/bin/python points to python3.
May you please tell me how can I explicit specify python version for `sleuthkit`?

**Comment by xabiugarte** [comment]
Hi s0i37,

The master branch of PyREBox is not ready for python3. There is a development version  compatible with python3, in the python3migration branch. The version is functional both for Windows and Linux targets, but the plugins have still not been ported to python3. Once the plugins have been ported fully tested, this will become the default version (merged into master).

So, you have 2 options:
* Create a python2 venv, install the requirements, and compile the master branch
* Create a python3 venv, install the requirements, and compile the python3migration branch. In this case, you will need to adapt the plugins yourself, as they may not run in python3 in their current status.
