### ISSUE TITLE
Can't release grab

### ISSUE THREAD

**Issue by Waterman178** [Cisco-Talos/pyrebox#107]
When I set a breakpoint in the process context(bp 0xffda4cff ), I click the button in the client, it will trigger the breakpoint, but when I press ctrl+alt+g it has no effect.

I installed debian 9 64 bit in vmware,then pyrebox is installed on debian system. The guest os is：win7x64

**Comment by xabiugarte** [comment]
Hi,

You can ask QEMU to set up a VNC session with -vnc 127.0.0.1:0 just like in the provided scripts. Then, you can connect with any VNC client to the screen session. That should prevent your mouse from being grabbed indefinitely.

**Comment by xabiugarte** [comment]
Closing this issue, please re-open it if necessary.
