### ISSUE TITLE
No process listed in 'ps' nor in 'vol pslist'

### ISSUE THREAD

**Issue by mdcrtse** [Cisco-Talos/pyrebox#11]
I know this issue was closed earlier but the solutions described don't seem to work for me.  The host is an Ubuntu Linux x86_64 with a KVM guest OS of WinXPSP3.  The pyrebox.conf file contains:

[MODULES]
scripts.script_example: False
scripts.script_example_min: False
scripts.vol_test: False
scripts.proc_bp: False
scripts.mem_write_test: False
scripts.page_write_execute_trigger: False
scripts.getset_var_example: False
scripts.bp_range_test: False
pyrebox_test.test_0_vmi_create_proc: False
pyrebox_test.test_1_block_begin: False
pyrebox_test.test_2_opt_block_begin: False
pyrebox_test.test_3_opt_insn_begin: False
pyrebox_test.test_4_mem_write: False
pyrebox_test.test_5_mem_read: False
pyrebox_test.test_6_keystroke: False
pyrebox_test.test_7_nic_test: False
pyrebox_test.test_8_opcode_range: False
pyrebox_test.test_9_tlb_and_context_change: False
pyrebox_test.test_10_block_end: False
pyrebox_test.test_11_insn_end: False

[VOL]
profile: WinXPSP3x86

Below I am including the commands invoked and the results displayed:

 root@erebor:~/pyrebox-master# ./pyrebox-i386 -monitor stdio -m 512 -usb -drive file=pyrebox/images/xpsp3.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -net nic,model=rtl8139 -net user

[*] Loading python component initialization script
[*] Platform: i386-softmmu
[*] Starting python module initialization
[*] Reading configuration
[*] Finished python module initialization
[*] Searching for KDBG...
QEMU 2.9.0 monitor - type 'help' for more information
(qemu) sh

[14] pyrebox> print_cpu
Showing results for cpu 0, indicate cpu index otherwise
========================================
               CPU 0
========================================
EAX      0x5a189bbb
ECX      0xffdffc70
EDX      0x00000000
EBX      0xffdffc70

ESP      0x80550f34
EBP      0x80550f50

ESI:     0xffdffc50
EDI:     0x81fb3150

EIP:     0xf85e1d3e
EFLAGS:  0x00000246

CR0:     0x8001003b
CR1:     0x00000000
CR2:     0x01250000
CR3:     0x00039000
CR4:     0x00000698

ES:      Sel: 00000023   Base: 00000000   Size: ffffffff   Flags: 00cff300
CS:      Sel: 00000008   Base: 00000000   Size: ffffffff   Flags: 00cf9a00
SS:      Sel: 00000010   Base: 00000000   Size: ffffffff   Flags: 00c09300
DS:      Sel: 00000023   Base: 00000000   Size: ffffffff   Flags: 00cff300
FS:      Sel: 00000030   Base: ffdff000   Size: 00001fff   Flags: ffc093df
GS:      Sel: 00000000   Base: 00000000   Size: 00000000   Flags: 00000000
LDT:     Sel: 00000000   Base: 00000000   Size: 00000000   Flags: 00008200
GDT:     Sel: 00000000   Base: 8003f000   Size: 000003ff   Flags: 00000000
IDT:     Sel: 00000000   Base: 8003f400   Size: 000007ff   Flags: 00000000
TR:      Sel: 00000028   Base: 80042000   Size: 000020ab   Flags: 80008904

[15] pyrebox> vol pslist

[16] pyrebox> ps
CPU 0 PGD: 39000 InKernel: 1
+------+---------+-----------+-----+-----+
| Name | Running | Monitored | PID | PGD |
+------+---------+-----------+-----+-----+
+------+---------+-----------+-----+-----+

[17] pyrebox>

**Comment by xabiugarte** [comment]
This issue could be happening if you have a local installation of volatility, which PyREBox is importing instead of the custom version installed via ./build.sh.

Until I work out a good solution for this, you can try uninstalling volatility if it is not a big issue for you. I will update this issue as soon as I solve the problem.

**Comment by mdcrtse** [comment]
That was the problem.  Thanks for the reply.  I removed the existing volatility program (using apt delete volatility) and then the vol pslist produced the following:
[1] pyrebox> vol pslist
Offset(V)  Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit                          
---------- -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------
0x821c8a00 System                    4      0     74      151 ------      0                                                              
0x82084da0 smss.exe                312      4      3       19 ------      0 2017-08-03 13:34:55 UTC+0000                                 
0x82043598 csrss.exe               408    312      9      303      0      0 2017-08-03 13:34:56 UTC+0000                                 
0x82057c68 winlogon.exe            432    312     25      536      0      0 2017-08-03 13:34:57 UTC+0000                                 
0x82087b28 services.exe            476    432     16      257      0      0 2017-08-03 13:34:58 UTC+0000                                 
0x82046700 lsass.exe               488    432     24      348      0      0 2017-08-03 13:34:58 UTC+0000                                 
0x820293c0 svchost.exe             664    476     18      162      0      0 2017-08-03 13:35:04 UTC+0000                                 
0x820154a0 svchost.exe             764    476      9      208      0      0 2017-08-03 13:35:20 UTC+0000                                 
0x81ffa508 svchost.exe             852    476     67     1103      0      0 2017-08-03 13:35:41 UTC+0000                                 
0x81ff0980 svchost.exe             936    476      5       59      0      0 2017-08-03 13:36:00 UTC+0000                                 
0x820458b0 spoolsv.exe            1240    476     13      127      0      0 2017-08-03 13:38:22 UTC+0000                                 
0x81fce020 svchost.exe            1396    476     11      165      0      0 2017-08-03 13:38:51 UTC+0000                                 
0x81fcb500 explorer.exe           1404   1332     15      274      0      0 2017-08-03 13:38:52 UTC+0000                                 
0x82126248 rundll32.exe           1832    476      2       65      0      0 2017-08-03 13:39:07 UTC+0000                                 
0x81f95da0 alg.exe                1916    476      7       98      0      0 2017-08-03 13:39:10 UTC+0000                                 
0x81f8bda0 wscntfy.exe            1944    852      1       28      0      0 2017-08-03 13:39:11 UTC+0000                                 



Thanks again for your help.

**Comment by xabiugarte** [comment]
Closing this issue. Commit 60e285673db9dde7b1ee81f44a9bda8c69f7f559 adds instructions on how to set a python virtual environment to install the python dependencies of PyREBox, to avoid conflicts with local installations of volatility. Also, the fix includes a check in PyREBox to detect if the imported volatility package is not the one installed by PyREBox, and displays a warning explaining how to proceed.
