### ISSUE TITLE
ps and proc not working

### ISSUE THREAD

**Issue by mdcrtse** [Cisco-Talos/pyrebox#13]
I downloaded the latest release and was able to get the volatility commands to work but the "ps" and "proc" commands do not work.  I am running  64 bit Ubuntu host with a 32 bit WinXPSP2 guest.

Here is the pyrebox.conf file:

[MODULES]
scripts.script_example: False
scripts.script_example_min: False
scripts.vol_test: False
scripts.proc_bp: False
scripts.mem_write_test: False
scripts.page_write_execute_trigger: False
scripts.getset_var_example: False
scripts.bp_range_test: False
pyrebox_test.test_0_vmi_create_proc: False
pyrebox_test.test_1_block_begin: False
pyrebox_test.test_2_opt_block_begin: False
pyrebox_test.test_3_opt_insn_begin: False
pyrebox_test.test_4_mem_write: False
pyrebox_test.test_5_mem_read: False
pyrebox_test.test_6_keystroke: False
pyrebox_test.test_7_nic_test: False
pyrebox_test.test_8_opcode_range: False
pyrebox_test.test_9_tlb_and_context_change: False
pyrebox_test.test_10_block_end: False
pyrebox_test.test_11_insn_end: False

[VOL]
profile: WinXPSP3x86

Here is the output from several commands related to the issue:

./pyrebox-x86_64 -monitor stdio -m 512 -usb -drive file=pyrebox/images/xpsp3.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -netdev user,id=network0 -device rtl8139,netdev=network0

[*] Loading python component initialization script
[*] Platform: x86_64-softmmu
[*] Starting python module initialization
[*] Reading configuration
[*] Finished python module initialization
[*] Searching for KDBG...
QEMU 2.9.0 monitor - type 'help' for more information
(qemu) sh

[1] pyrebox> vol pslist
Offset(V)  Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit                          
---------- -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------
0x821c8a00 System                    4      0     75      235 ------      0                                                              
0x82090368 smss.exe                312      4      3       19 ------      0 2017-08-07 17:43:23 UTC+0000                                 
0x81ff7320 csrss.exe               412    312     11      314      0      0 2017-08-07 17:43:24 UTC+0000                                 
0x820a3020 winlogon.exe            436    312     24      531      0      0 2017-08-07 17:43:24 UTC+0000                                 
0x81ffd330 services.exe            488    436     16      241      0      0 2017-08-07 17:43:25 UTC+0000                                 
0x81fec978 lsass.exe               500    436     22      349      0      0 2017-08-07 17:43:25 UTC+0000                                 
0x81fde020 svchost.exe             712    488     19      194      0      0 2017-08-07 17:43:32 UTC+0000                                 
0x81fcb4a8 svchost.exe             788    488      9      215      0      0 2017-08-07 17:43:43 UTC+0000                                 
0x81fb1b70 svchost.exe             904    488     66     1147      0      0 2017-08-07 17:44:02 UTC+0000                                 
0x81f9db60 svchost.exe            1040    488      6       84      0      0 2017-08-07 17:44:14 UTC+0000                                 
0x81f7d220 svchost.exe            1140    488     14      197      0      0 2017-08-07 17:45:07 UTC+0000                                 
0x81fee468 spoolsv.exe            1368    488     13      116      0      0 2017-08-07 17:46:23 UTC+0000                                 
0x81fdb8e0 explorer.exe           1524   1460     13      309      0      0 2017-08-07 17:46:45 UTC+0000                                 
0x81f420a8 wscntfy.exe             832    904      1       28      0      0 2017-08-07 17:47:04 UTC+0000                                 
0x82110c28 alg.exe                 732    488      7      104      0      0 2017-08-07 17:47:06 UTC+0000                                 
0x82103b88 cmd.exe                 584   1524      1       30      0      0 2017-08-07 17:47:18 UTC+0000                                 

[2] pyrebox> proc 584
Process 584 not found

[3] pyrebox> proc 1524
Process 1524 not found

[4] pyrebox> proc cmd.exe
Process cmd.exe not found

[5] pyrebox> ps
CPU 0 PGD: aed000 InKernel: 1
+------+---------+-----------+-----+-----+
| Name | Running | Monitored | PID | PGD |
+------+---------+-----------+-----+-----+
+------+---------+-----------+-----+-----+

[6] pyrebox> print_cpu
Showing results for cpu 0, indicate cpu index otherwise
========================================
               CPU 0
========================================
RAX      0x0000000000000543
RCX      0x00000000ffdffc50
RDX      0x0000000080010031
RBX      0x00000000ffdff000
R8       0x0000000000000000
R9       0x0000000000000000
R10      0x0000000000000000
R11      0x0000000000000000
R12      0x0000000000000000
R13      0x0000000000000000
R14      0x0000000000000000
R15      0x0000000000000000

RSP      0x0000000080549c54
RBP      0x00000000ffdff980

RSI:     0x0000000080552740
RDI:     0x00000000805529a0

RIP:     0x00000000806d89ba
RFLAGS:  0x0000000000000297

CR0:     0x000000008001003b
CR1:     0x0000000000000000
CR2:     0x0000000000e6fd20
CR3:     0x0000000000aed000
CR4:     0x00000000000006f8

ES:      Sel: 00000023   Base: 0000000000000000   Size: ffffffff   Flags: 00cff300
CS:      Sel: 00000008   Base: 0000000000000000   Size: ffffffff   Flags: 00cf9a00
SS:      Sel: 00000010   Base: 0000000000000000   Size: ffffffff   Flags: 00c09300
DS:      Sel: 00000023   Base: 0000000000000000   Size: ffffffff   Flags: 00cff300
FS:      Sel: 00000030   Base: 00000000ffdff000   Size: 00001fff   Flags: ffc093df
GS:      Sel: 00000000   Base: 0000000000000000   Size: 00000000   Flags: 00000000
LDT:     Sel: 00000000   Base: 0000000000000000   Size: 00000000   Flags: 00008200
GDT:     Sel: 00000000   Base: 000000008003f000   Size: 000003ff   Flags: 00000000
IDT:     Sel: 00000000   Base: 000000008003f400   Size: 000007ff   Flags: 00000000
TR:      Sel: 00000028   Base: 0000000080042000   Size: 000020ab   Flags: 80008904

[7] pyrebox>

**Comment by xabiugarte** [comment]
Hi,

You should be using ./pyrebox-i386 instead of ./pyrebox-x86_64  in order to emulate a 32 bit guest. 

Hope this helps!

**Comment by mdcrtse** [comment]
Thanks, that did the trick.

**Comment by 0xcpu** [comment]
Hi,

I'm experiencing a similar issue on an Ubuntu 18.04 x64 host and Windows 7 x64 guest.
Command to instantiate pyrebox `./pyrebox-x86_64 -m 2048 -monitor stdio -usb -drive file=images/win7x64.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -boot d -enable-kvm`

Here are information from the host:
```
QEMU 2.12.0 monitor - type 'help' for more information
(qemu) VNC server running on 127.0.0.1:5900
sh

[1] pyrebox> ps
CPU 0 PGD: 0 InKernel: 1
+------+---------+-----------+-----+-----+
| Name | Running | Monitored | PID | PGD |
+------+---------+-----------+-----+-----+
+------+---------+-----------+-----+-----+

[2] pyrebox> vol pslist
Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit                          
------------------ -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------
0xfffffa8001850b30 System                    4      0     74      483 ------      0 2018-08-28 10:17:25 UTC+0000                                 
0xfffffa8002b1f040 smss.exe                248      4      4       29 ------      0 2018-08-28 10:17:25 UTC+0000                                 
0xfffffa800372c9d0 csrss.exe               328    320      8      358      0      0 2018-08-28 10:17:27 UTC+0000                                 
0xfffffa8001977300 wininit.exe             376    320      7       87      0      0 2018-08-28 10:17:28 UTC+0000                                 
0xfffffa8002ceb670 csrss.exe               388    368      7      147      1      0 2018-08-28 10:17:28 UTC+0000                                 
0xfffffa8001907300 winlogon.exe            428    368      6      125      1      0 2018-08-28 10:17:28 UTC+0000                                 
0xfffffa8002acd830 services.exe            472    376     20      216      0      0 2018-08-28 10:17:29 UTC+0000                                 
0xfffffa80091ff4f0 lsass.exe               480    376      9      554      0      0 2018-08-28 10:17:29 UTC+0000                                 
0xfffffa8003538b30 lsm.exe                 488    376     10      150      0      0 2018-08-28 10:17:29 UTC+0000                                 
0xfffffa8002a316d0 svchost.exe             596    472     15      355      0      0 2018-08-28 10:17:29 UTC+0000                                 
0xfffffa80018b53a0 svchost.exe             664    472     10      238      0      0 2018-08-28 10:17:29 UTC+0000                                 
0xfffffa8003ae3730 svchost.exe             712    472     16      341      0      0 2018-08-28 10:17:29 UTC+0000                                 
0xfffffa8002a08890 svchost.exe             788    472     22      425      0      0 2018-08-28 10:17:29 UTC+0000                                 
0xfffffa8002ab7060 svchost.exe             876    472     44      767      0      0 2018-08-28 10:17:29 UTC+0000                                 
0xfffffa8002b1bb30 svchost.exe            1008    472     15      313      0      0 2018-08-28 10:17:29 UTC+0000                                 
0xfffffa8002dbcb30 svchost.exe             320    472     21      409      0      0 2018-08-28 10:17:30 UTC+0000                                 
0xfffffa80030a2290 spoolsv.exe             312    472     13      282      0      0 2018-08-28 10:17:30 UTC+0000                                 
0xfffffa8002fd7600 svchost.exe            1028    472     22      313      0      0 2018-08-28 10:17:30 UTC+0000                                 
0xfffffa8003756b30 svchost.exe            1156    472     18      225      0      0 2018-08-28 10:17:30 UTC+0000                                 
0xfffffa8003881280 VSSVC.exe              1616    472      6      122      0      0 2018-08-28 10:17:32 UTC+0000                                 
0xfffffa80038fc5c0 svchost.exe            1648    472      6       69      0      0 2018-08-28 10:17:32 UTC+0000                                 
0xfffffa8002b0a880 taskhost.exe           1764    472      9      155      1      0 2018-08-28 10:17:33 UTC+0000                                 
0xfffffa80109f1060 dwm.exe                1824    788      5       72      1      0 2018-08-28 10:17:33 UTC+0000                                 
0xfffffa8003a50340 explorer.exe           1836   1816     26      630      1      0 2018-08-28 10:17:33 UTC+0000                                 
0xfffffa8002b095b0 SearchIndexer.         1264    472     14      614      0      0 2018-08-28 10:17:39 UTC+0000                                 
0xfffffa8003b74b30 wmpnetwk.exe            284    472     12      217      0      0 2018-08-28 10:17:39 UTC+0000                                 
0xfffffa800287d430 SearchProtocol         2024   1264      7      225      1      0 2018-08-28 10:17:40 UTC+0000                                 
0xfffffa800286e670 SearchFilterHo          848   1264      5       78      0      0 2018-08-28 10:17:40 UTC+0000                                 
0xfffffa8002aa2b30 iexplore.exe           1104   1772      0 --------      1      0 2018-08-28 10:17:58 UTC+0000   2018-08-28 10:18:15 UTC+0000  

[3] pyrebox> print_cpu
Showing results for cpu 0, indicate cpu index otherwise
========================================
               CPU 0
========================================
RAX      0x0000000000000020
RCX      0x0000000000000000
RDX      0x000000000000ffff
RBX      0x000000000000ffff
R8       0x0000000000000000
R9       0x0000000000000000
R10      0x0000000000000000
R11      0x0000000000000000
R12      0x0000000000000000
R13      0x0000000000000000
R14      0x0000000000000000
R15      0x0000000000000000

RSP      0x0000000000006de4
RBP      0x0000000000000000

RSI:     0x0000000000000000
RDI:     0x0000000000002300

RIP:     0x0000000000000018
RFLAGS:  0x0000000000000046

CR0:     0x0000000000000010
CR1:     0x0000000000000000
CR2:     0x0000000000000000
CR3:     0x0000000000000000
CR4:     0x0000000000000000

ES:      Sel: 0000f000   Base: 00000000000f0000   Size: ffffffff   Flags: 00809300
CS:      Sel: 0000ca80   Base: 00000000000ca800   Size: ffffffff   Flags: 00809b00
SS:      Sel: 00000000   Base: 0000000000000000   Size: ffffffff   Flags: 00809300
DS:      Sel: 00000000   Base: 0000000000000000   Size: ffffffff   Flags: 00809300
FS:      Sel: 00000000   Base: 0000000000000000   Size: ffffffff   Flags: 00809300
GS:      Sel: 00000000   Base: 0000000000000000   Size: ffffffff   Flags: 00809300
LDT:     Sel: 00000000   Base: 0000000000000000   Size: 0000ffff   Flags: 00008200
GDT:     Sel: 00000000   Base: 0000000000000000   Size: 00000000   Flags: 00000000
IDT:     Sel: 00000000   Base: 0000000000000000   Size: 000003ff   Flags: 00000000
TR:      Sel: 00000000   Base: 0000000000000000   Size: 0000ffff   Flags: 00008b00
```
`systeminfo` from guest:
![systeminfo](https://user-images.githubusercontent.com/2598963/44726235-f2a30900-aadf-11e8-829a-ecbcc6ffad04.png)

Thank you!

**Comment by 0xcpu** [comment]
Ok, I've figured it out, it's because I ran `pyrebox` with `KVM` enabled.
