### ISSUE TITLE
 bad argument to internal function

### ISSUE THREAD

**Issue by aoprea1982** [Cisco-Talos/pyrebox#18]
Got this error. 

Also attaching a screenshot.
#####################
(qemu) sh
../Objects/longobject.c:998: bad argument to internal function
Traceback (most recent call last):
  File "/root/pyrebox/pyrebox/init.py", line 124, in pyrebox_ipython_shell
    from ipython_shell import start_shell
SystemError: ../Objects/longobject.c:998: bad argument to internal function
#####################

![rebox19](https://user-images.githubusercontent.com/16059481/30111462-a7d34bec-9348-11e7-96d1-be77432d5994.jpg)

1) Operating system used to compile and run PyREBox.
Ubuntu 16.04   16.04.1-Ubuntu SMP 

2) The specific operating system version and emulation target you are using.
Windows 7 Ultimate SP1 
using  Win7SP1x64 volatility

3) Shell command / script / task you were trying to run.
Just started the shell. 

Attaching pyrebox.conf screenshot
![rebox20](https://user-images.githubusercontent.com/16059481/30111520-ece73ad6-9348-11e7-9213-c200711d4c26.jpg)

**Comment by aoprea1982** [comment]
Also i cannot list the running processes from debugee
![rebox21](https://user-images.githubusercontent.com/16059481/30111842-37942ec6-934a-11e7-836b-bad2e6bbcde4.jpg)

**Comment by aoprea1982** [comment]
It worked with Win7 32bit SP1 


![rebox26](https://user-images.githubusercontent.com/16059481/30141788-85c8df92-93b8-11e7-8748-6548b0f72679.jpg)

**Comment by xabiugarte** [comment]
I am currently working to reproduce the error, I will update the bug once I have some information / fix.

**Comment by xabiugarte** [comment]
Hi,

Commit 9b84178d1d57b5fdf7dba598352c257505b8ad60 solves the issue. Thank you for the thorough description of the bug!
