### ISSUE TITLE
Problems with sym_to_va and va_to_sym

### ISSUE THREAD

**Issue by jholgui** [Cisco-Talos/pyrebox#20]
i have always the next error with this 2 functions (sym_to_va and va_to_sym):

"Process with PGD %x not found"

In other functions PGD is correct. I have analyzed pyrebox/api.py and i think the next code exit very fast (never scan all procs, then never will find the proc):

> else:
>            raise ValueError("Process with PGD %x not found"  % pgd)

I have commented this else and functions finds the symbol or the va.

Greets,
JoseMi

**Comment by jholgui** [comment]
With this change i have this result: 

[2] pyrebox> proc notepad
Process set to 8b0:1f82f000:notepad.exe

[3] pyrebox(8b0)> x createprocess
[*] Updating symbol list... Be patient, this may take a while
[*] Searching for symbols with name createprocess
+--------------+-------------------------------+-------------+
|    Module    |            Function           |     Address |
+--------------+-------------------------------+-------------+
| kernel32.dll |         CreateProcessA        |    77328840 |
| kernel32.dll |      CreateProcessAsUserW     |    7729a420 |
| kernel32.dll |     CreateProcessInternalA    |    77327b70 |
| kernel32.dll |     CreateProcessInternalW    |    772ae7b0 |
| kernel32.dll |         CreateProcessW        |    772b1bb0 |
| kernel32.dll |         CreateProcessA        |    77328840 |
| kernel32.dll |      CreateProcessAsUserW     |    7729a420 |
| kernel32.dll |     CreateProcessInternalA    |    77327b70 |
| kernel32.dll |     CreateProcessInternalW    |    772ae7b0 |
| kernel32.dll |         CreateProcessW        |    772b1bb0 |
|  ntdll.dll   |        NtCreateProcess        |    77501d30 |
|  ntdll.dll   |       NtCreateProcessEx       |    775017e0 |
|  ntdll.dll   |   RtlCreateProcessParameters  |    774fddf0 |
|  ntdll.dll   |  RtlCreateProcessParametersEx |    774e92a0 |
|  ntdll.dll   |   RtlCreateProcessReflection  |    775a3f90 |
|  ntdll.dll   | RtlpCreateProcessRegistryInfo |    774d9230 |
|  ntdll.dll   |        ZwCreateProcess        |    77501d30 |
|  ntdll.dll   |       ZwCreateProcessEx       |    775017e0 |
| SHELL32.dll  |     SHCreateProcessAsUserW    | 7fefdb2e2d8 |
+--------------+-------------------------------+-------------+

[4] pyrebox(8b0)> print hex(api.sym_to_va(0x1f82f000,"kernel32.dll","CreateProcessW"))
0x772b1bb0L

**Comment by jholgui** [comment]
I have had differents errors with va_to_sym. This is my function modified now:

   import vmi
    for proc_pid,proc_pgd in vmi.modules:
        if proc_pgd == pgd:
            for module in vmi.modules[proc_pid,proc_pgd].values():
                offset = (addr - module.get_base())
                if offset > 0 and offset < module.get_size():
                    syms = module.get_symbols()
                    for ordinal,symbol_offset,name in syms:
                        if offset == symbol_offset:
                                return (module.get_name(), name)
    return None

PR is coming ... is it correct this changes? 

Greets,
JoseMi

**Comment by jholgui** [comment]
[4] pyrebox> proc notepad
Process set to 114:1c7e6000:notepad.exe

[12] pyrebox(114)> x createprocess
[*] Updating symbol list... Be patient, this may take a while
[*] Searching for symbols with name createprocess
+--------------+-------------------------------+----------+
|    Module    |            Function           |  Address |
+--------------+-------------------------------+----------+
| kernel32.dll |         CreateProcessA        | 77328840 |
| kernel32.dll |      CreateProcessAsUserW     | 7729a420 |
| kernel32.dll |     CreateProcessInternalA    | 77327b70 |
| kernel32.dll |     CreateProcessInternalW    | 772ae7b0 |
| kernel32.dll |         CreateProcessW        | 772b1bb0 |
| kernel32.dll |         CreateProcessA        | 77328840 |
| kernel32.dll |      CreateProcessAsUserW     | 7729a420 |
| kernel32.dll |     CreateProcessInternalA    | 77327b70 |
| kernel32.dll |     CreateProcessInternalW    | 772ae7b0 |
| kernel32.dll |         CreateProcessW        | 772b1bb0 |
|  ntdll.dll   |        NtCreateProcess        | 77501d30 |
|  ntdll.dll   |       NtCreateProcessEx       | 775017e0 |
|  ntdll.dll   |   RtlCreateProcessParameters  | 774fddf0 |
|  ntdll.dll   |  RtlCreateProcessParametersEx | 774e92a0 |
|  ntdll.dll   |   RtlCreateProcessReflection  | 775a3f90 |
|  ntdll.dll   | RtlpCreateProcessRegistryInfo | 774d9230 |
|  ntdll.dll   |        ZwCreateProcess        | 77501d30 |
|  ntdll.dll   |       ZwCreateProcessEx       | 775017e0 |
|  CSRSRV.dll  |        CsrCreateProcess       | 00006374 |
|  CSRSRV.dll  |    CsrDeferredCreateProcess   | 00006344 |
+--------------+-------------------------------+----------+

[13] pyrebox(114)> api.va_to_sym(0x1c7e6000,0x772b1bb0)
[13]          out> (u'kernel32.dll', 'CreateProcessW')

**Comment by xabiugarte** [comment]
Hi JoseMi,

Thanks for pointing out this error and your suggestions. This error should be fixed in commit f41c23176080cd326383bb55632f4bbec90e5473.

Regards,

Xabier
