### ISSUE TITLE
Reload modules with changes

### ISSUE THREAD

**Issue by jholgui** [Cisco-Talos/pyrebox#22]
I'm developing a module for pyrebox, but i have problems to reload (with changes) this module from Qemu console. My procedure is:

import_module funcap
..... (module execution and finish)
unload_module 1

After i want to load the same module but this module has changes. I have to reboot the machine to apply the changes .. is it this normal ?? other procedure to reload modules ?? 

Thank you!!

**Comment by xabiugarte** [comment]
Hi!

Commit 180b873d88e451cf4cd9c2b80b977c8b3ac476bc adds the functionality you need. Just type reload_module to have your module reloaded. Remember to remove all the callbacks in the clean() function (as the provided examples show). The reload process will first call the clean() function of your module, and then the "initialize_callbacks" function again. Also, any global variable you keep in your script will be lost once the script is reloaded.

Hope this helps!

**Comment by jholgui** [comment]
Wow, thank you i'm going to test :-)
