### ISSUE TITLE
List ntoskrnl.exe modules and others ...

### ISSUE THREAD

**Issue by jholgui** [Cisco-Talos/pyrebox#24]
It would be very nice to list ntoskrnl.exe modules with lm command. In the other hand, it would be useful that x command could list ntoskrnl symbols. 

![example_modules_ntoskrnl](https://user-images.githubusercontent.com/2709307/30899271-81572c50-a35f-11e7-8dd0-86bf7982e0ec.png)
![exports_ntoskrnl](https://user-images.githubusercontent.com/2709307/30899381-f2f65188-a35f-11e7-8128-a9caf0dcacba.png)
![ksecdd_imports](https://user-images.githubusercontent.com/2709307/30899390-f8558b6c-a35f-11e7-85cd-a5263e02fd70.png)
![ksecdd_exports](https://user-images.githubusercontent.com/2709307/30899393-fe472896-a35f-11e7-89ae-e1818080ea5b.png)

**Comment by xabiugarte** [comment]
Commit ca7a2911b25a30a6e492a1d41fcd6d457b390116 includes this functionality.

Thanks for the suggestion!
