### ISSUE TITLE
Saving snapshot with savevm hangs

### ISSUE THREAD

**Issue by takadito15** [Cisco-Talos/pyrebox#25]
Hi,

Tested with both Win7 x86 and x64 vms, on different environments. 
Taking snapshot with savevm works with KVM (-enable-vm), but hangs without it.
What could  be the reason?

Thanks

**Comment by xabiugarte** [comment]
It was a deadlock that was introduced when qemu was upgraded to its latest version.

Thanks for reporting the bug!
