### ISSUE TITLE
guest compiling errors

### ISSUE THREAD

**Issue by Bondey** [Cisco-Talos/pyrebox#28]
Hi,

I'm trying to compile the agent (with Mingw dependences installed) and i'm having the following error:
`#make

make -C libseh -f GNUmakefile
make[1]: se entra en el directorio '/home/user/test/pyrebox/guest/win/libseh'
i686-w64-mingw32-gcc -O2 -Wall -g -std=c99 -fno-strict-aliasing  -o build/common.o -c common/common.c
In file included from common/../seh.h:36:0,
                 from common/common.c:33:
common/../os/windows/seh-support.h:35:10: error fatal: ../../common/config.h: No existe el fichero o el directorio
 #include "../../common/config.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilación terminada.
make[1]: *** [GNUmakefile:36: build/common.o] Error 1
make[1]: se sale del directorio '/home/user/test/pyrebox/guest/win/libseh'
make: *** [Makefile:77: libseh/build/libseh.a] Error 2
`

I'm trying to compile it from ArchLinux, maybe this is the problem, but i think it shouldn't, everything else compiled and worked like a charm. This is such an awesome project!

**Comment by xabiugarte** [comment]
Hi!

Please, check out the last commit (66a06d8c6954bd4e9e5ee1d730ae7e269b95020d). There was an error in the .gitignore preventing a file from being comitted.

Thanks for reporting the issue! Your help is really appreciated! Please re-open this issue if the problem persists after the fix. 

Thanks!

**Comment by Bondey** [comment]
Yep, it now works nice :)

Thanks to you.
