### ISSUE TITLE
windows_agent Crash

### ISSUE THREAD

**Issue by simhigo** [Cisco-Talos/pyrebox#29]
Host : Ubuntu 16.04.03 
Guest: Windows 7 SP1x64  KN Build.

Win_Agent_64 is running in Guest OS.

But Agent_strncmp called when it's crash

**Comment by simhigo** [comment]
Solved  
I Add -enable-kvm option custom 
del -enable-kvm option custom agent run 
Thanks

**Comment by simhigo** [comment]
Agent run when this error view in host os.

Guest agent with PGD 3d606000 was killed, but you can start it again![plugins.guest_agent] HostFilePlugin: Guest agent with PGD 6a32a000 was killed, but you can start it again!
Warning: no scancode found for keysym 0
Warning: no scancode found for keysym 0
Warning: no scancode found for keysym 0
Warning: no scancode found for keysym 0
Traceback (most recent call last):
  File "/home/*******/pyrebox/pyrebox/api_internal.py", line 108, in function_wrapper
    f(*args)
  File "/home/*******/pyrebox/plugins/guest_agent.py", line 436, in __opcode_range_callback
    self.__printer("Exception occurred on opcode callback: %s" % str(e))
  File "/home/*******/pyrebox/pyrebox/api_internal.py", line 85, in print_internal
    string_to_print = (f % args)
TypeError: not enough arguments for format string

**Comment by xabiugarte** [comment]
Hi @simhigo, 

The last commit (1c75abb9cd8c5cf7a4f92862f294333417656234) updates the way things are printed. It may not solve your problem, but it may provide us a little more information. Could you please update to the latest version and try to reproduce your error?

Thanks!

**Comment by xabiugarte** [comment]
Closing this issue as there has been no feedback for a long time.

**Comment by simhigo** [comment]
Hi
I have a questsion.

Does not WinAgent_x64.exe  support kvm yet?
