### ISSUE TITLE
Undefined name 'module_name'

### ISSUE THREAD

**Issue by cclauss** [Cisco-Talos/pyrebox#3]
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__

```
./pyrebox/init.py:89:52: F821 undefined name 'module_name'
        pp_warning("[*]  Module %s not loaded\n" % module_name)
                                                   ^
```
https://github.com/Cisco-Talos/pyrebox/blob/master/pyrebox/init.py#L89

**Comment by xabiugarte** [comment]
It should be fixed in commit e66b1e1ddfb4ec54c154d515c3c9a0fffef86745.
