### ISSUE TITLE
Question: GTK Window, Not VNC?

### ISSUE THREAD

**Issue by bridgeythegeek** [Cisco-Talos/pyrebox#39]
Hi all,

It seems that even if I don't specify `-vnc`, PyREBox spawns vnc anyway:
```
(venv-pyrebox) root@3a6bf416bc2f:/pyrebox# ./pyrebox-x86_64 -m 1024 -drive file=/slw/panda-Win7SP1x64/hdd.img -monitor stdio -conf pyrebox.conf.Win7SP1x64

[*] Loading python component initialization script
[*] Platform: x86_64-softmmu
[*] Starting python module initialization
[*] Reading configuration from 'pyrebox.conf.Win7SP1x64'
[*] Searching for KDBG...
[*] Initializing scripts...
[*] Finished python module initialization
QEMU 2.10.0 monitor - type 'help' for more information
(qemu) VNC server running on 127.0.0.1:5900
[*] KPCR found at fffff80002841d00!!
[*] KDBG found at fffff800028400a0!!
```

But I don't want to use VNC. I want the window (GTK?) that opens, as PANDA does.

Is this possible?

Thanks,
Adam

**Comment by xabiugarte** [comment]
Hi Adam,

You will just need to install the dependencies and rebuild PyREBox. On an Ubuntu system, it would be:

$ sudo apt-get install libgtk-3-dev
$ ./build.sh --reconfigure

Then, do not forget to remove the "-vnc" option when you run PyREBox.

Regards,

Xabier
