### ISSUE TITLE
ERROR: glib-2.22 gthread-2.0 is required to compile QEMU

### ISSUE THREAD

**Issue by gbiagomba** [Cisco-Talos/pyrebox#41]
Hello, 

I keep getting the noted error when running the build.sh but I have qemu installed and i can seem to locate those missing libraries. 

Below is the screenshot to the error am getting.

![image](https://user-images.githubusercontent.com/5851606/37538924-8a9db6fe-2928-11e8-93fc-02dc4a7b5806.png)

**Comment by xabiugarte** [comment]
Hi,

it looks like you have some unmet library dependencies. Please make sure you have the following packages:

(on a Debian / Ubuntu based distribution:)

apt-get install build-essential zlib1g-dev pkg-config libglib2.0-dev binutils-dev libboost-all-dev autoconf libtool libssl-dev libpixman-1-dev libpython-dev python-pip python-capstone virtualenv

For a complete Build&Install guide, you can refer to this documentation: https://pyrebox.readthedocs.io/en/latest/quickstart.html#building-pyrebox

Hope this helps,

**Comment by xabiugarte** [comment]
Hi,

I am closing this issue. Please re-open it if you have any problems.

Regards,

Xabier

**Comment by gbiagomba** [comment]
I am still having dependencies issues still but i will troubleshoot this further

**Comment by xabiugarte** [comment]
If I understand correctly, you had problems with glib/gthread. Could you run the following command and paste here the output?

$ dpkg -l | grep "libglib"

**Comment by gbiagomba** [comment]
ii  libglib-object-introspection-perl         0.046-1+b1                                   amd64        Perl bindings for gobject-introspection libraries
ii  libglib-perl                              3:1.328-1+b1                                 amd64        interface to the GLib and GObject libraries
ii  libglib2.0-0:amd64                        2.58.1-2                                     amd64        GLib library of C routines
ii  libglib2.0-bin                            2.58.1-2                                     amd64        Programs for the GLib library
ii  libglib2.0-data                           2.58.1-2                                     all          Common files for GLib library
ii  libglibmm-2.4-1v5:amd64                   2.58.0-1                                     amd64        C++ wrapper for the GLib toolkit (shared libraries)

**Comment by xabiugarte** [comment]
Hi gbiagomba,

It seems you are missing the development libraries for glib:

please, make sure you install all the dependencies:

apt-get install build-essential zlib1g-dev pkg-config libglib2.0-dev binutils-dev libboost-all-dev autoconf libtool libssl-dev libpixman-1-dev libpython-dev python-pip python-capstone virtualenv

Note that this list of packages includes **libglib2.0-dev**, which seems to be your unmet dependency.

Thanks,

**Comment by gbiagomba** [comment]
@xabiugarte That seems to have fixed it thank you

**Comment by EnderNightLord-ChromeBook** [comment]
yes thanks for that. It helped me too.

**Comment by walaa-a** [comment]
I am running into the same issue on a Mac. I tried using brew install build-essential ..... but I get an error:
Error: No available formula with the name "build-essential" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by xabiugarte** [comment]
Hi,

At the moment PyREBox has not yet been tested on OSX. It has been successfully used and compiled in different GNU/Linux distributions, docker (which can run on OSX, Windows and Linux), and the Linux subsystem in Windows 10.

Anyway, QEMU can be compiled in OSX, so, it should be possible to compile PyREBox too. Here you can find some documentation about QEMU's dependencies, and process to compile it: https://wiki.qemu.org/Hosts/Mac

If you go forward and compile it for OSX, please do not hesitate to open a pull request if any modification on the project was needed.

Thanks!

**Comment by Flyour** [comment]
Thanks, it help me too

**Comment by clockzhong** [comment]
I installed the following :

`apt-get install build-essential zlib1g-dev pkg-config libglib2.0-dev binutils-dev libboost-all-dev autoconf libtool libssl-dev libpixman-1-dev  python-capstone
`
Then this dependent issue fixed in my env.

**Comment by kerrygip** [comment]
> 

This worked for me in 2022

**Comment by andykui** [comment]
This worked for me in 2022、09

**Comment by DxExWxExY** [comment]
if you are trying to cross-compile for arm, you need to enable support for it.
* DPKG: `sudo dpkg --add-architecture arm64`
* Update `sources.list` to include `[arch=amd64]` for ports URLs (varies per distro).

In my case I only had to install the following arm64 packages: `libglib2.0-dev:arm64` `libpixman-1-dev:arm64`, but check the list provided by @clockzhong in the comment above.

I am cross-compiling on Ubuntu 20.04 Focal, so my `sources.list` ended up looking like this:
```
#deb cdrom:[Ubuntu 20.04.4 LTS _Focal Fossa_ - Release amd64 (20220223)]/ focal main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ focal main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu/ focal main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ focal universe
# deb-src http://us.archive.ubuntu.com/ubuntu/ focal universe
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ focal-updates universe
# deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ focal multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ focal multiverse
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ focal-updates multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu focal partner
# deb-src http://archive.canonical.com/ubuntu focal partner

deb [arch=amd64] http://security.ubuntu.com/ubuntu focal-security main restricted
# deb-src http://security.ubuntu.com/ubuntu focal-security main restricted
deb [arch=amd64] http://security.ubuntu.com/ubuntu focal-security universe
# deb-src http://security.ubuntu.com/ubuntu focal-security universe
deb [arch=amd64] http://security.ubuntu.com/ubuntu focal-security multiverse
# deb-src http://security.ubuntu.com/ubuntu focal-security multiverse

# This system was installed using small removable media
# (e.g. netinst, live or single CD). The matching "deb cdrom"
# entries were disabled at the end of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual.

deb [arch=arm64] http://ports.ubuntu.com/ focal main restricted
deb [arch=arm64] http://ports.ubuntu.com/ focal-updates main restricted
deb [arch=arm64] http://ports.ubuntu.com/ focal universe
deb [arch=arm64] http://ports.ubuntu.com/ focal-updates universe
deb [arch=arm64] http://ports.ubuntu.com/ focal multiverse
deb [arch=arm64] http://ports.ubuntu.com/ focal-updates multiverse
deb [arch=arm64] http://ports.ubuntu.com/ focal-backports main restricted universe multiverse
```
