### ISSUE TITLE
Support vmware esxi

### ISSUE THREAD

**Issue by Ghostly-consciousness** [Cisco-Talos/pyrebox#42]
Hello. Is it possible to support the esxi? I tried to try to implement it. But it did not work. I tried to understand why this did not happen. I learned about the fact that the download occurred only before the bootloader.

**Comment by xabiugarte** [comment]
Hi,

Thanks for the comment. I understand that you are trying to emulate ESXi inside PyREBox. Is that right?

If this is the case:

VMWare ESXi is not a supported operating system in PyREBox at this moment. It would require QEMU's full system emulator to support emulation of Intel VT extensions.

There are some blog posts explaining how to install VMWare ESXi inside QEMU-KVM, making use of nested virtualization. Nevertheless, PyREBox is based on QEMU's full system emulation, and is not compatible with KVM. For a more detailed explanation, you can read the comments on issue #2 (https://github.com/Cisco-Talos/pyrebox/issues/2).

I am closing this issue, but feel free to re-open it if your question / issues persist.

Regards,

Xabier
