### ISSUE TITLE
attach to existing xen vm

### ISSUE THREAD

**Issue by asabellico** [Cisco-Talos/pyrebox#45]
Hello, is it possible to attach PyREbox to an existing XEN domain?

Thank you

**Comment by xabiugarte** [comment]
HI asabellico,

PyREBox is based on full-system emulation on QEMU. Although it might be possible to support other backends in the future, for the moment it does not support hardware assisted virtualization. You can see https://github.com/Cisco-Talos/pyrebox/issues/2 for further reference.

Regards,

Xabier
