### ISSUE TITLE
Question: guest_agent.copy_file and guest_agent.execute_file

### ISSUE THREAD

**Issue by vc0622** [Cisco-Talos/pyrebox#47]
Hi pyrebox developer(s),

I am working a project that utilizes pyrebox to analyze binary programs. I followed pyrebox documentation and created a 32-bit Windows 7 virtual machine. I used Win7SP1x86 profile and commands such as "ps" and "vol pslist" worked fine. I could see the processes running in the VM, however when I tried to use guest_agent.copy(path_to_my_file, "C:\\temp.exe"), the file did not appear in the VM. Moreover, assuming that the file was inside the VM "somehow" I executed guest_agent.execute_file("C:\\temp.exe") and predictably nothing happened. It might have been a little mistake but it would be very helpful if you could point me to the right direction. 

Thank you.

**Comment by xabiugarte** [comment]
Hi vc0622,

There are a few things that are necessary for the agent to work:

1. You must compile the agent (go to the guest/win/ path, and run  $make. That will generate 2 binaries, one for 32 bits, and one for 64 bits, and 2 configuration files, one per binary. The configuration files are generated under the root directory of the project. Just make sure that your pyrebox.conf (https://github.com/Cisco-Talos/pyrebox/blob/master/pyrebox.conf.WinXPSP3x86#L31) points to the correct agent configuration file, and that the name you use for the generated binary matches the name in the configuration. If you use the default names, you will not need to change any configuration file.
2. Copy the agent binary to the guest. For this, you can use an emulated USB device. there are some indications about how to do this on the documentation (https://pyrebox.readthedocs.io/en/latest/quickstart.html#loading-a-usb-image-with-files). For other alternative options, check the QEMU documentation. 
3. You must run the agent in the guest. For this, start your VM, and when it is booted up, run a cmd.exe shell and run the agent. Also, you must enable the guest_agent plugin on the pyrebox.conf file, setting the corresponding line to True (https://github.com/Cisco-Talos/pyrebox/blob/master/pyrebox.conf.WinXPSP3x86#L2). If this script is not loaded on the host, then the agent will print an error message and exit. If, on the contrary, the guest agent plugin is loaded on the guest, the agent will enter a loop, waiting for commands. At this moment, you can create a snapshot from the QEMU monitor, by using the savevm *snapshot_name* command. 
4. At this point, you have the agent fully configured and running. The next time you start pyrebox, you just need to load that snapshot (loadvm command, or using a command line argument), and make sure that the guest_agent plugin is loaded in the guest. You can then use the agent.copy_file and agent.execute_file to copy and run files.

I hope little guide helps with the problem. I am closing the issue, but please reopen it if the problems persist.

Regards,

Xabier

**Comment by vc0622** [comment]
Hi Xabier,

Thank you for your help. Everything works great.
