### ISSUE TITLE
Problems compiling dev branch 

### ISSUE THREAD

**Issue by jholgui** [Cisco-Talos/pyrebox#54]
Ubuntu 16.04:

ui/input-keymap.c:8:45: fatal error: ui/input-keymap-atset1-to-qcode.c: No existe el archivo o el directorio
compilation terminated.

Best regards.

**Comment by xabiugarte** [comment]
Fixed in commit 79679b00bdab99075f81a5547884b8d48fdd95fb. Closing issue.
