### ISSUE TITLE
No rule to make target - autorun process hooking

### ISSUE THREAD

**Issue by SecsAndCyber** [Cisco-Talos/pyrebox#60]
When running...
https://github.com/Cisco-Talos/pyrebox/blob/72193bfd2c235cd2d0ce998911ba685827a2d476/autorun/autorun.py#L228

It fails at...
https://github.com/Cisco-Talos/pyrebox/blob/b5965efff35dd3b72e4f2f7806930d2d868251b6/pyrebox/api.py#L1036-L1052

Adding logging for stdout/stderr for that subprocess call captured...
` make: *** No rule to make target 'triggers/trigger_bpwh_memrange-i386-softmmu.so'.  Stop.`

Solved: The subprocess starts the `make` call in the current working directory rather than using the pyrebox directory. Those make calls fail if the pyrebox execution was started from other directories.

**Comment by SecsAndCyber** [comment]
https://github.com/Cisco-Talos/pyrebox/pull/61

**Comment by xabiugarte** [comment]
Thanks for your PR @SecsAndCyber !!
