### ISSUE TITLE
Problem with win 7 install

### ISSUE THREAD

**Issue by pinpiin** [Cisco-Talos/pyrebox#73]
Hi

Why when i use the following command on CentOS 7:
./pyrebox-x86_64 -m 2096 -monitor stdio -usb -drive file=qemu/images/seven.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -cdrom qemu/images/ru-en_win7_sp1_x86-x64_18in1_activated_v7.iso -boot d
I get the error:
[*] Loading python component initialization script
[*] Platform: x86_64-softmmu
[*] Starting python module initialization
[*] Reading configuration from 'pyrebox.conf'
/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py:726: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
[*] Searching for KDBG...
[*] Initializing scripts...
[*] Finished python module initialization
QEMU 2.12.0 monitor - type 'help' for more information
(qemu) VNC server running on ::1:5900

[SLEUTHKIT]
Opening image - Size: 10737418240
[!] Error, could not open volume system
Cannot determine partition type

[SLEUTHKIT]
Opening image - Size: 18186240
[!] Error, could not open volume system
Cannot determine partition type

**Comment by pinpiin** [comment]
I try to use qcow image with istalled win7 sp1. I use the following command:
./pyrebox-x86_64 -m 2048 -monitor stdio -usb -drive file=qemu/images/win7.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -netdev user,id=network0 -device rtl8139,netdev=network0

I get the following output:
[*] Loading python component initialization script
[*] Platform: x86_64-softmmu
[*] Starting python module initialization
[*] Reading configuration from 'pyrebox.conf'
[*] Searching for KDBG...
[*] Initializing scripts...
[*] Finished python module initialization
QEMU 2.12.0 monitor - type 'help' for more information
(qemu) VNC server running on ::1:5900

[SLEUTHKIT]
Opening image - Size: 10737418240
[*] Found volume system of type DOS Partition Table at 0, number of partitions: 4
    [#] Partition 0 - Start sector: 0 - Number of sectors: 1 - Desc: Primary Table (#0)
    [#] Partition 1 - Start sector: 0 - Number of sectors: 800 - Desc: Unallocated
    [#] Partition 2 - Start sector: 800 - Number of sectors: 13ff000 - Desc: NTFS / exFAT (0x07)
        [+] Found file system type ntfs at 100000
    [#] Partition 3 - Start sector: 13ff800 - Number of sectors: 800 - Desc: Unallocated

I try use pyrebox:
(qemu) sh

[1] pyrebox> ps
CPU 0 PGD: 187000 InKernel: 1
+------+---------+-----------+-----+-----+
| Name | Running | Monitored | PID | PGD |
+------+---------+-----------+-----+-----+
+------+---------+-----------+-----+-----+

But output looks like os don't boot.
Can you help me?

**Comment by pinpiin** [comment]
Ok, i have problem with os image.
No it looks better:
[10] pyrebox(4)> ps
CPU 0 PGD: 187000 InKernel: 1
+--------------+---------+-----------+------------------+------------------+
|     Name     | Running | Monitored |              PID |              PGD |
+--------------+---------+-----------+------------------+------------------+
| >> System << |  (0-k)  |           | 0000000000000004 | 0000000000187000 |
|   smss.exe   |         |           | 0000000000000138 | 000000001b5b8000 |
|  csrss.exe   |         |           | 0000000000000198 | 0000000018e28000 |
|   smss.exe   |         |           | 00000000000001b4 | 00000000193ca000 |
| wininit.exe  |         |           | 00000000000001bc | 000000001892e000 |
+--------------+---------+-----------+------------------+------------------+
But i dont see win interface. How to enable it?

**Comment by xabiugarte** [comment]
Hi, 

First of all, sorry for this delayed response. I didn't realize that this thread was still open.

If you add the following option to your command, QEMU will create a VNC server you can connect to by using any VNC client such as vinagre. 

`-vnc 127.0.0.1:0`

Hope this helps,

Xabier
