### ISSUE TITLE
ram size too large

### ISSUE THREAD

**Issue by Waterman178** [Cisco-Talos/pyrebox#75]
**I want to simulate win7x64.My host system is debian.I want to set the guest's memory size to 4G.But it prompts me to support up to 2047MB.What happened？**

(pyrebox_venv) root@debian:/home/author/Downloads/pyrebox# ./pyrebox-x86_64 -m 2048 -monitor stdio -usb -drive file=images/Windows7x64.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -cdrom images/Windows7x64.iso -boot d

[*] Loading python component initialization script
[*] Platform: x86_64-softmmu
[*] Starting python module initialization
[*] Reading configuration from 'pyrebox.conf'
[*] Searching for KDBG...
[*] Initializing scripts...
[*]  Loading python module plugins.guest_agent
[plugins.guest_agent] [*]    Initializing guest_agent plugin
[*]  Loading python module mw_monitor.mw_monitor
[*]  Module plugins.guest_agent already imported, did you want to reload it instead?
[mw_monitor.mw_monitor] Reading mw_monitor configuration...
[mw_monitor.mw_monitor] Copying host file to guest, using agent...
[mw_monitor.mw_monitor] Initializing callbacks
[mw_monitor.mw_monitor] No process matching that process name, deferring process detection
[mw_monitor.mw_monitor] Initializing process creation callback
[mw_monitor.mw_monitor] Adding dumper commands
[mw_monitor.mw_monitor] Initialized callbacks
[*] Finished python module initialization
qemu-system-x86_64: at most 2047 MB RAM can be simulated

**Comment by xabiugarte** [comment]
Hi,

Based on the command you pasted on the issue, you are creating a guest machine with 2048 mb of physical memory. Nevertheless, QEMU/PyREBox is telling you that at most 2047 MB can be simulated. 

Based on what you said in issue #76, you are installing PyREBox on a Debian VM. How much physical memory did you assign to that Debian VM? Note that the Debian system (under vmware), must have enough memory to hold the guest QEMU system (4G), + the debian operating system, + the QEMU process itself. For a 4GB Windows 7, I would assign at least, 8 GB to the Debian system.

I am closing this issue and following up on #76. Reopen this issue if adding more memory to the Debian system doesn't work for you.

**Comment by Waterman178** [comment]
![default](https://user-images.githubusercontent.com/14991217/53303140-e555b400-38a1-11e9-9c41-72c4d27b9b7b.PNG)
My virtual machine memory has always been 8G 4 core,but it  prompts me to support up to 2047MB,The key issue is that the cpu usage of the guest system is 100%,so it is very slow.

**Comment by Waterman178** [comment]
> Hi,
> 
> Based on the command you pasted on the issue, you are creating a guest machine with 2048 mb of physical memory. Nevertheless, QEMU/PyREBox is telling you that at most 2047 MB can be simulated.
> 
> Based on what you said in issue #76, you are installing PyREBox on a Debian VM. How much physical memory did you assign to that Debian VM? Note that the Debian system (under vmware), must have enough memory to hold the guest QEMU system (4G), + the debian operating system, + the QEMU process itself. For a 4GB Windows 7, I would assign at least, 8 GB to the Debian system.
> 
> I am closing this issue and following up on #76. Reopen this issue if adding more memory to the Debian system doesn't work for you.

![default](https://user-images.githubusercontent.com/14991217/53303214-c1df3900-38a2-11e9-9c84-ee6dd82b82c4.PNG)
My virtual machine memory has always been 8G 4 core,but it prompts me to support up to 2047MB,The key issue is that the cpu usage of the guest system is 100%,so it is very slow.

**Comment by xabiugarte** [comment]
Ok, I am reopening the issue myself to take a look and see why it is not supporting more than 2047mb of ram

**Comment by xabiugarte** [comment]
Hi, this might be the explanation to your RAM problem:

https://github.com/Cisco-Talos/pyrebox/blob/d46ca5d01b38042361859d41c04f1ee1b7195451/qemu/vl.c#L4515

`    if (!xen_enabled()) {
        /* On 32-bit hosts, QEMU is limited by virtual address space */
        if (ram_size > (2047 << 20) && HOST_LONG_BITS == 32) {
            error_report("at most 2047 MB RAM can be simulated");
            exit(1);
        }
    }`

Is your Debian VM a 32 bit OS? If so, that would explain why you cannot allocate more then 2GB of RAM, and also why the system is specially slow, as emulated 64 bit instructions are being translated to a 32 bit target.

**Comment by Waterman178** [comment]
> Hi, this might be the explanation to your RAM problem:
> 
> [pyrebox/qemu/vl.c](https://github.com/Cisco-Talos/pyrebox/blob/d46ca5d01b38042361859d41c04f1ee1b7195451/qemu/vl.c#L4515)
> 
> Line 4515 in [d46ca5d](/Cisco-Talos/pyrebox/commit/d46ca5d01b38042361859d41c04f1ee1b7195451)
> 
>  error_report("at most 2047 MB RAM can be simulated"); 
> ` if (!xen_enabled()) { /* On 32-bit hosts, QEMU is limited by virtual address space */ if (ram_size > (2047 << 20) && HOST_LONG_BITS == 32) { error_report("at most 2047 MB RAM can be simulated"); exit(1); } }`
> 
> Is your Debian VM a 32 bit OS? If so, that would explain why you cannot allocate more then 2GB of RAM, and also why the system is specially slow, as emulated 64 bit instructions are being translated to a 32 bit target.

I'm sorry to waste your time.I did install a 32-bit system.I didn't notice that the mirror I downloaded was 32-bit.

**Comment by xabiugarte** [comment]
No worries :), I will close this issue then. Please reopen it if needed.
