### ISSUE TITLE
QEMU version bump

### ISSUE THREAD

**Issue by richsurgenor** [Cisco-Talos/pyrebox#78]
With 4.0.0 out, what is the best way to upgrade the current QEMU version?

**Comment by xabiugarte** [comment]
I am planning on doing this upgrade soon.

**Comment by richsurgenor** [comment]
Thanks. Is there a reason to not make qemu a submodule for this project? Seems like it would make updating to future versions easier.

**Comment by xabiugarte** [comment]
PyREBox is actually fairly decoupled from QEMU, but it is not a submodule, as PyREBox requires modifications on the QEMU code to perform its instrumentation. The reason why this time it is taking me longer to do the upgrade is that the new QEMU version will bring multithreaded TCG, which might break stuff, so I want to make sure I can allocate some time to upgrade and properly test it.

**Comment by richsurgenor** [comment]
I went ahead and upgraded this and submitted a pull request (#80 ). It seems to work as I'd expect.

**Comment by xabiugarte** [comment]
Hi,

Thanks for the pull request!. The aspect that worries me most is the multi-threaded TCG. It seems that support for MTTCG is enabled by default for i386 and x64 targets, but it might not make any difference if the VM is not configured with several processors.

I will try this out.

Thanks!

**Comment by richsurgenor** [comment]
I noticed that the git submodules needed updating, and also that some files were not added because of the "/qemu" in the gitignore. Sorry about that.

**Comment by Waterman178** [comment]
> I noticed that the git submodules needed updating, and also that some files were not added because of the "/qemu" in the gitignore. Sorry about that.
> 
> I tested using 4 cores on Windows XP. Mainly attaching to a proc and reading physical/virtual memory. Seems to work so far. Thanks.

Does this updated version support MTCG features?

**Comment by richsurgenor** [comment]
As far as I can tell, yes.

**Comment by xabiugarte** [comment]
Closing this issue as it should be complete.
