### ISSUE TITLE
PMemAddressSpace has no method called "translate"

### ISSUE THREAD

**Issue by Waterman178** [Cisco-Talos/pyrebox#85]
When I type this command: "%vol psxview" it prompts me this : PMemAddressSpace has no method called "translate".I found that its base class does not have this method.So I modified two places. It looks like it works.
![QQ截图20190603220611](https://user-images.githubusercontent.com/14991217/58808182-15a0b180-864c-11e9-8373-95ccb7277a85.png)
![QQ截图20190603220625](https://user-images.githubusercontent.com/14991217/58808184-16d1de80-864c-11e9-95c1-507bfe616dfb.png)

**Comment by xabiugarte** [comment]
Could you please submit a Pull request with this modification so that I can merge it?

Thanks for the fix!
