### ISSUE TITLE
need more than 2 values to unpack

### ISSUE THREAD

**Issue by Waterman178** [Cisco-Talos/pyrebox#86]
I also found a problem but it has been resolved. Please check it here.
[https://github.com/volatilityfoundation/volatility/issues/610](url)

**Comment by xabiugarte** [comment]
This will require to upgrade the version of volatility. Assigning this to myself so that I can complete it.

**Comment by Waterman178** [comment]
> This will require to upgrade the version of volatility. Assigning this to myself so that I can complete it.

The version of the volatility plugin in your project is very old.What would be the conflict if I update it to the latest version?

**Comment by xabiugarte** [comment]
Volatility version upgraded, closing issue.
