### ISSUE TITLE
qemu-system-x86_64: Parameter 'type' expects a netdev backend type

### ISSUE THREAD

**Issue by BrandonGDossantos** [Cisco-Talos/pyrebox#94]
I installed WinXP SP1, closed it, then launched this command to start it with net enabled. 

`./pyrebox-x86_64 -m 4096 -monitor stdio -usb -drive file=/images/xpsp1.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -netdev user,id=network0 -device rtl8139,netdev=network0`

See the attached screenshot for the confusing error.
![Screenshot from 2019-11-21 19-37-45](https://user-images.githubusercontent.com/17682268/69388386-b0428a80-0c96-11ea-95b8-2a8ab5aa3b56.png)

**Comment by xabiugarte** [comment]
Can you please pull the latest commit from the master branch and run a complete rebuild (make clean; ./build.sh --reconfigure)? The latest commit should fix some problems with the SLIRP submodule, that enables user networking.

https://github.com/Cisco-Talos/pyrebox/commit/8d192a57f28860fa4144316c7c4ec79e4fcfbbf9

**Comment by xabiugarte** [comment]
If that doesn't work, please try to clone it again and start from scratch

**Comment by BrandonGDossantos** [comment]
I cloned and started from scratch and it worked, thanks for your attention. Should I be fetching updates often?

**Comment by xabiugarte** [comment]
Yes, it is convenient. I'd suggest to always fetch the latest version from the master branch. That branch should be the most stable one, and when bugs are found, I patch them directly. The rest of branches are mainly for new developments.
