### ISSUE TITLE
vnc connection refused

### ISSUE THREAD

**Issue by m155p1nk** [Cisco-Talos/pyrebox#97]
Hi, 

i installed pyrebox on manjaro linux with your provided Dockerfile and followed the instructions in the documentation by executing the following commands:
`qemu-img create -f qcow2 -o compat=0.10 images/win7.qcow2 40G`

`./pyrebox-x86_64 -m 2048 -monitor stdio -usb -drive file=images/win7.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -cdrom images/win7x64.iso -boot d `

In my terminal, I get this output:
![2019-12-04-112553_437x337_scrot](https://user-images.githubusercontent.com/49272454/70134709-e6b1d980-1688-11ea-83bb-33a6c9eb1625.png)

although when trying to connect to the vnc server from my host system, I get an error from vnc viewer: 

![2019-12-04-111410_561x330_scrot](https://user-images.githubusercontent.com/49272454/70134853-24aefd80-1689-11ea-8d91-351f1a5788e7.png)

any ideas on how to fix this?
Thank you and Regards

**Comment by xabiugarte** [comment]
Hi,

You might need to enable VNC by adding the following argument:

-vnc 127.0.0.1:0

Then connect to VNC on 127.0.0.1

**Comment by xabiugarte** [comment]
Additionally, I recommend to do the OS install process with a clean QEMU installation (not pyrebox), with KVM enabled. The install process will be much faster. Then, once the image is ready, you can shut down the machine, and start it with pyrebox (and, if needed, take a snapshot once it is booted in pyrebox).

**Comment by xabiugarte** [comment]
I am closing this issue now, if you still have problems, do not hesitate to reopen it.
