### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by BlackLuny** [Cisco-Talos/pyrebox#98]
./pyrebox-i386 -m 256
Traceback (most recent call last):
  File "/home/luny/pyrebox/pyrebox/pyrebox/init.py", line 26, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable
./pyrebox-i386: line 3: 69328 Segmentation fault      (core dumped) LD_LIBRARY_PATH=$BASEDIR/sleuthkit/tsk/.libs:$LD_LIBRARY_PATH $BASEDIR/qemu/i386-softmmu/qemu-system-i386 "$@"

**Comment by BrandonGDossantos** [comment]
Make sure that you have installed the packages from the requirements.txt by `sudo pip install -r requirements.txt`. Then run the program as the superuser, `sudo ./pyrebox....`

**Comment by xabiugarte** [comment]
Thanks Brandon for the quick answer! I am closing this issue as it has already been resolved.

**Comment by BlackLuny** [comment]
I have pip installed all requirements in requirements.txt manually.And rebuild all after "make clean".But still not working.

(pyrebox_venv) luny@ubuntu:~/pyrebox/pyrebox$ sudo ./pyrebox-i386 -m 256 -monitor stdio -usb -drive file=images/xpsp3.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -cdrom images/WinXP.iso -boot d -enable-kvm
Traceback (most recent call last):
  File "/home/luny/pyrebox/pyrebox/pyrebox/init.py", line 26, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable
./pyrebox-i386: line 3: 124420 Segmentation fault      (core dumped) LD_LIBRARY_PATH=$BASEDIR/sleuthkit/tsk/.libs:$LD_LIBRARY_PATH $BASEDIR/qemu/i386-softmmu/qemu-system-i386 "$@"
(pyrebox_venv) luny@ubuntu:~/pyrebox/pyrebox$ pip install prettytable
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: prettytable in ./pyrebox_venv/lib/python2.7/site-packages (0.7.2)
(pyrebox_venv) luny@ubuntu:~/pyrebox/pyrebox$

**Comment by BlackLuny** [comment]
OK! It works now while removing "sudo".
